wsl = false
no-multigrid = false
# multigrid = false
vsync = true
maximized = true
srgb = false
idle = true
frame = "transparent"
tabs = false
theme = "auto"
macos-native-tabs = false

macos-tab-prev-hotkey = "ctrl+shift+left"
macos-tab-next-hotkey = "ctrl+shift+right"

[font]
size = 16

[[font.normal]]
# family = "JetBrainsMono Nerd Font Mono"
family = "Maple Mono NF CN"
style = "SemiBold"

[[font.bold]]
family = "Maple Mono NF CN"

[[font.italic]]
family = "Maple Mono NF CN"

[[font.bold_italic]]
family = "Maple Mono NF CN"

[font.features]
# "JetBrainsMono Nerd Font Mono" = ["+zero", "+ss19"]
"Maple Mono NF CN" = ["cv35=1", "cv61=1", "cv62=1", "+ss05"]
